export enum SpriteId {
  ArrowLong = 'arrow-long-right',
  ArrowShort = 'arrow-down',
  Camera = 'camera',
  Cat = 'cat',
  Checkmark = 'checkmark',
  Close = 'close',
  EyeClosed = 'eye-closed',
  EyeOpened = 'eye-opened',
  Facebook = 'facebook',
  Grid = 'square-four',
  Instagram = 'instagram',
  Linkedin = 'linkedin',
  List = 'menu',
  Loader = 'loader',
  Logo = 'logo',
  Search = 'search',
  Sort = 'sort-ascending',
  StarEmpty = 'star',
  StarFill = 'star-fill',
  Success = 'check-circle-fill',
  Vk = 'vk',
  Warning = 'warning-circle-fill',
}
